/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as DotIndexRouteImport } from './index'
import { Route as DotToolsRouteImport } from './tools'
import { Route as DotSecretsRouteImport } from './secrets'
import { Route as DotPoliciesRouteImport } from './policies'
import { Route as DotResumeDotexecutionIdRouteImport } from './resume.$executionId'
import { Route as DotIntegrationsDotnamespaceRouteImport } from './integrations.$namespace'
import { Route as DotPluginsDotpluginIdDotsplatRouteImport } from './plugins.$pluginId.$'
import { Route as DotIntegrationsDotaddDotpluginKeyRouteImport } from './integrations.add.$pluginKey'

const DotIndexRoute = DotIndexRouteImport.update({
  id: '/{-$orgSlug}/',
  path: '/{-$orgSlug}/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotToolsRoute = DotToolsRouteImport.update({
  id: '/{-$orgSlug}/tools',
  path: '/{-$orgSlug}/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DotSecretsRoute = DotSecretsRouteImport.update({
  id: '/{-$orgSlug}/secrets',
  path: '/{-$orgSlug}/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const DotPoliciesRoute = DotPoliciesRouteImport.update({
  id: '/{-$orgSlug}/policies',
  path: '/{-$orgSlug}/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const DotResumeDotexecutionIdRoute = DotResumeDotexecutionIdRouteImport.update({
  id: '/{-$orgSlug}/resume/$executionId',
  path: '/{-$orgSlug}/resume/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotIntegrationsDotnamespaceRoute =
  DotIntegrationsDotnamespaceRouteImport.update({
    id: '/{-$orgSlug}/integrations/$namespace',
    path: '/{-$orgSlug}/integrations/$namespace',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotPluginsDotpluginIdDotsplatRoute =
  DotPluginsDotpluginIdDotsplatRouteImport.update({
    id: '/{-$orgSlug}/plugins/$pluginId/$',
    path: '/{-$orgSlug}/plugins/$pluginId/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotIntegrationsDotaddDotpluginKeyRoute =
  DotIntegrationsDotaddDotpluginKeyRouteImport.update({
    id: '/{-$orgSlug}/integrations/add/$pluginKey',
    path: '/{-$orgSlug}/integrations/add/$pluginKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$orgSlug}/policies': typeof DotPoliciesRoute
  '/{-$orgSlug}/secrets': typeof DotSecretsRoute
  '/{-$orgSlug}/tools': typeof DotToolsRoute
  '/{-$orgSlug}/': typeof DotIndexRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotResumeDotexecutionIdRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotPluginsDotpluginIdDotsplatRoute
}
export interface FileRoutesByTo {
  '/{-$orgSlug}/policies': typeof DotPoliciesRoute
  '/{-$orgSlug}/secrets': typeof DotSecretsRoute
  '/{-$orgSlug}/tools': typeof DotToolsRoute
  '/{-$orgSlug}': typeof DotIndexRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotResumeDotexecutionIdRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotPluginsDotpluginIdDotsplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$orgSlug}/policies': typeof DotPoliciesRoute
  '/{-$orgSlug}/secrets': typeof DotSecretsRoute
  '/{-$orgSlug}/tools': typeof DotToolsRoute
  '/{-$orgSlug}/': typeof DotIndexRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotResumeDotexecutionIdRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotPluginsDotpluginIdDotsplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
  id:
    | '__root__'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotPoliciesRoute: typeof DotPoliciesRoute
  DotSecretsRoute: typeof DotSecretsRoute
  DotToolsRoute: typeof DotToolsRoute
  DotIndexRoute: typeof DotIndexRoute
  DotIntegrationsDotnamespaceRoute: typeof DotIntegrationsDotnamespaceRoute
  DotResumeDotexecutionIdRoute: typeof DotResumeDotexecutionIdRoute
  DotIntegrationsDotaddDotpluginKeyRoute: typeof DotIntegrationsDotaddDotpluginKeyRoute
  DotPluginsDotpluginIdDotsplatRoute: typeof DotPluginsDotpluginIdDotsplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$orgSlug}/': {
      id: '/{-$orgSlug}/'
      path: '/{-$orgSlug}'
      fullPath: '/{-$orgSlug}/'
      preLoaderRoute: typeof DotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/tools': {
      id: '/{-$orgSlug}/tools'
      path: '/{-$orgSlug}/tools'
      fullPath: '/{-$orgSlug}/tools'
      preLoaderRoute: typeof DotToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/secrets': {
      id: '/{-$orgSlug}/secrets'
      path: '/{-$orgSlug}/secrets'
      fullPath: '/{-$orgSlug}/secrets'
      preLoaderRoute: typeof DotSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/policies': {
      id: '/{-$orgSlug}/policies'
      path: '/{-$orgSlug}/policies'
      fullPath: '/{-$orgSlug}/policies'
      preLoaderRoute: typeof DotPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/resume/$executionId': {
      id: '/{-$orgSlug}/resume/$executionId'
      path: '/{-$orgSlug}/resume/$executionId'
      fullPath: '/{-$orgSlug}/resume/$executionId'
      preLoaderRoute: typeof DotResumeDotexecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/$namespace': {
      id: '/{-$orgSlug}/integrations/$namespace'
      path: '/{-$orgSlug}/integrations/$namespace'
      fullPath: '/{-$orgSlug}/integrations/$namespace'
      preLoaderRoute: typeof DotIntegrationsDotnamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/plugins/$pluginId/$': {
      id: '/{-$orgSlug}/plugins/$pluginId/$'
      path: '/{-$orgSlug}/plugins/$pluginId/$'
      fullPath: '/{-$orgSlug}/plugins/$pluginId/$'
      preLoaderRoute: typeof DotPluginsDotpluginIdDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/add/$pluginKey': {
      id: '/{-$orgSlug}/integrations/add/$pluginKey'
      path: '/{-$orgSlug}/integrations/add/$pluginKey'
      fullPath: '/{-$orgSlug}/integrations/add/$pluginKey'
      preLoaderRoute: typeof DotIntegrationsDotaddDotpluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DotPoliciesRoute: DotPoliciesRoute,
  DotSecretsRoute: DotSecretsRoute,
  DotToolsRoute: DotToolsRoute,
  DotIndexRoute: DotIndexRoute,
  DotIntegrationsDotnamespaceRoute: DotIntegrationsDotnamespaceRoute,
  DotResumeDotexecutionIdRoute: DotResumeDotexecutionIdRoute,
  DotIntegrationsDotaddDotpluginKeyRoute:
    DotIntegrationsDotaddDotpluginKeyRoute,
  DotPluginsDotpluginIdDotsplatRoute: DotPluginsDotpluginIdDotsplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
