/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupMcpRouteImport } from './routes/bare/setup-mcp'
import { Route as LoginRouteImport } from './routes/bare/login'
import { Route as CreateOrgRouteImport } from './routes/bare/create-org'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport } from './../../../packages/react/src/routes/index'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport } from './../../../packages/react/src/routes/tools'
import { Route as SecretsRouteImport } from './routes/app/secrets'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport } from './../../../packages/react/src/routes/policies'
import { Route as OrgRouteImport } from './routes/app/org'
import { Route as BillingRouteImport } from './routes/app/billing'
import { Route as ApiKeysRouteImport } from './routes/app/api-keys'
import { Route as ResumeDotexecutionIdRouteImport } from './routes/app/resume.$executionId'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport } from './../../../packages/react/src/routes/integrations.$namespace'
import { Route as Billing_DotplansRouteImport } from './routes/app/billing_.plans'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport } from './../../../packages/react/src/routes/integrations.add.$pluginKey'

const SetupMcpRoute = SetupMcpRouteImport.update({
  id: '/setup-mcp',
  path: '/setup-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport.update({
    id: '/{-$orgSlug}/',
    path: '/{-$orgSlug}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport.update({
    id: '/{-$orgSlug}/tools',
    path: '/{-$orgSlug}/tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/{-$orgSlug}/secrets',
  path: '/{-$orgSlug}/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport.update({
    id: '/{-$orgSlug}/policies',
    path: '/{-$orgSlug}/policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgRoute = OrgRouteImport.update({
  id: '/{-$orgSlug}/org',
  path: '/{-$orgSlug}/org',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/{-$orgSlug}/billing',
  path: '/{-$orgSlug}/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/{-$orgSlug}/api-keys',
  path: '/{-$orgSlug}/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeDotexecutionIdRoute = ResumeDotexecutionIdRouteImport.update({
  id: '/{-$orgSlug}/resume/$executionId',
  path: '/{-$orgSlug}/resume/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/$namespace',
      path: '/{-$orgSlug}/integrations/$namespace',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Billing_DotplansRoute = Billing_DotplansRouteImport.update({
  id: '/{-$orgSlug}/billing_/plans',
  path: '/{-$orgSlug}/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/add/$pluginKey',
      path: '/{-$orgSlug}/integrations/add/$pluginKey',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/{-$orgSlug}/api-keys': typeof ApiKeysRoute
  '/{-$orgSlug}/billing': typeof BillingRoute
  '/{-$orgSlug}/org': typeof OrgRoute
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof SecretsRoute
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/billing/plans': typeof Billing_DotplansRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof ResumeDotexecutionIdRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}
export interface FileRoutesByTo {
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/{-$orgSlug}/api-keys': typeof ApiKeysRoute
  '/{-$orgSlug}/billing': typeof BillingRoute
  '/{-$orgSlug}/org': typeof OrgRoute
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof SecretsRoute
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/billing/plans': typeof Billing_DotplansRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof ResumeDotexecutionIdRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/{-$orgSlug}/api-keys': typeof ApiKeysRoute
  '/{-$orgSlug}/billing': typeof BillingRoute
  '/{-$orgSlug}/org': typeof OrgRoute
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof SecretsRoute
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/billing_/plans': typeof Billing_DotplansRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof ResumeDotexecutionIdRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-org'
    | '/login'
    | '/setup-mcp'
    | '/{-$orgSlug}/api-keys'
    | '/{-$orgSlug}/billing'
    | '/{-$orgSlug}/org'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/billing/plans'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-org'
    | '/login'
    | '/setup-mcp'
    | '/{-$orgSlug}/api-keys'
    | '/{-$orgSlug}/billing'
    | '/{-$orgSlug}/org'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}'
    | '/{-$orgSlug}/billing/plans'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
  id:
    | '__root__'
    | '/create-org'
    | '/login'
    | '/setup-mcp'
    | '/{-$orgSlug}/api-keys'
    | '/{-$orgSlug}/billing'
    | '/{-$orgSlug}/org'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/billing_/plans'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CreateOrgRoute: typeof CreateOrgRoute
  LoginRoute: typeof LoginRoute
  SetupMcpRoute: typeof SetupMcpRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BillingRoute: typeof BillingRoute
  OrgRoute: typeof OrgRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  SecretsRoute: typeof SecretsRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  Billing_DotplansRoute: typeof Billing_DotplansRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  ResumeDotexecutionIdRoute: typeof ResumeDotexecutionIdRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-mcp': {
      id: '/setup-mcp'
      path: '/setup-mcp'
      fullPath: '/setup-mcp'
      preLoaderRoute: typeof SetupMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/': {
      id: '/{-$orgSlug}/'
      path: '/{-$orgSlug}'
      fullPath: '/{-$orgSlug}/'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/tools': {
      id: '/{-$orgSlug}/tools'
      path: '/{-$orgSlug}/tools'
      fullPath: '/{-$orgSlug}/tools'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/secrets': {
      id: '/{-$orgSlug}/secrets'
      path: '/{-$orgSlug}/secrets'
      fullPath: '/{-$orgSlug}/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/policies': {
      id: '/{-$orgSlug}/policies'
      path: '/{-$orgSlug}/policies'
      fullPath: '/{-$orgSlug}/policies'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/org': {
      id: '/{-$orgSlug}/org'
      path: '/{-$orgSlug}/org'
      fullPath: '/{-$orgSlug}/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/billing': {
      id: '/{-$orgSlug}/billing'
      path: '/{-$orgSlug}/billing'
      fullPath: '/{-$orgSlug}/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/api-keys': {
      id: '/{-$orgSlug}/api-keys'
      path: '/{-$orgSlug}/api-keys'
      fullPath: '/{-$orgSlug}/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/resume/$executionId': {
      id: '/{-$orgSlug}/resume/$executionId'
      path: '/{-$orgSlug}/resume/$executionId'
      fullPath: '/{-$orgSlug}/resume/$executionId'
      preLoaderRoute: typeof ResumeDotexecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/$namespace': {
      id: '/{-$orgSlug}/integrations/$namespace'
      path: '/{-$orgSlug}/integrations/$namespace'
      fullPath: '/{-$orgSlug}/integrations/$namespace'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/billing_/plans': {
      id: '/{-$orgSlug}/billing_/plans'
      path: '/{-$orgSlug}/billing/plans'
      fullPath: '/{-$orgSlug}/billing/plans'
      preLoaderRoute: typeof Billing_DotplansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/add/$pluginKey': {
      id: '/{-$orgSlug}/integrations/add/$pluginKey'
      path: '/{-$orgSlug}/integrations/add/$pluginKey'
      fullPath: '/{-$orgSlug}/integrations/add/$pluginKey'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CreateOrgRoute: CreateOrgRoute,
  LoginRoute: LoginRoute,
  SetupMcpRoute: SetupMcpRoute,
  ApiKeysRoute: ApiKeysRoute,
  BillingRoute: BillingRoute,
  OrgRoute: OrgRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute,
  SecretsRoute: SecretsRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute,
  Billing_DotplansRoute: Billing_DotplansRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute,
  ResumeDotexecutionIdRoute: ResumeDotexecutionIdRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { startInstance } from './start.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>

    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
